version: '3'
services:
  devcontainer:
    image: rust-dev:latest
    runtime: crun
    network_mode: host
    privileged: true
    environment:
      - XDG_RUNTIME_DIR=/run/user/1000
      - WAYLAND_DISPLAY=wayland-1
      - CARGO_HOME=/root/.cargo
      - HTTPS_PROXY=http://localhost:5780
    volumes:
      - ../../.vscode-server:/root/.vscode-server
      - ../../.cargo:/root/.cargo
      - ..:/workspaces:cached
      - /run/dbus/:/run/dbus/
      - /run/user/1000:/run/user/1000
    working_dir: /workspaces
    command: sleep infinity