version: '3'
services:
  devcontainer:
    image: rust-dev:latest
    network_mode: host
    privileged: true
    environment:
      - CARGO_HOME=/root/.cargo
      - HTTPS_PROXY=http://192.168.1.22:5780
    volumes:
      - ../../.vscode-server:/root/.vscode-server
      - ../../.cargo:/root/.cargo
      - ..:/workspaces:cached
      - /run/dbus/:/run/dbus/
      - /run/user/1000:/run/user/1000
    working_dir: /workspaces
    command: sleep infinity