name: Android-Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release-android:
    runs-on: ubuntu-22.04
    container: mingc/android-build-box:latest
    permissions:
      contents: write


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set NDK_HOME
        run: echo "NDK_HOME=$ANDROID_HOME/ndk/$(find $ANDROID_HOME/ndk -maxdepth 1 -mindepth 1 -type d -print -quit | xargs basename)" >> $GITHUB_ENV

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # - name: Install ubuntu dependencies
      #   run: |
      #     sudo apt update
      #     sudo apt install libwebkit2gtk-4.1-dev \
      #       build-essential \
      #       curl \
      #       wget \
      #       file \
      #       libxdo-dev \
      #       libssl-dev \
      #       libayatana-appindicator3-dev \
      #       librsvg2-dev

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Init Android Project
        run: |
          pnpm tauri android init --ci

      - name: Build Tauri application
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: ${{ github.ref_name }}
          args: android build --apk --ci