name: Android-Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release-android:
    runs-on: ubuntu-22.04
    container: mingc/android-build-box:latest
    permissions:
      contents: write


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set NDK_HOME
        run: echo "NDK_HOME=$ANDROID_HOME/ndk/$(find $ANDROID_HOME/ndk -maxdepth 1 -mindepth 1 -type d -print -quit | xargs basename)" >> $GITHUB_ENV

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Init Android Project
        run: |
          pnpm tauri android init --ci

      - name: Build Android application
        run: |
          pnpm tauri android build --apk --target aarch64 --ci

      - name: Find APK file
        id: find_apk
        run: |
          APK_PATH=$(find src-tauri/target/aarch64-linux-android/release/bundle/apk -name "*.apk" -print -quit)
          echo "APK_PATH=$APK_PATH" >> $GITHUB_OUTPUT
          echo "APK_NAME=$(basename $APK_PATH)" >> $GITHUB_OUTPUT

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: ${{ steps.find_apk.outputs.APK_PATH }}

